config/routes.rb
Rails.application.routes.draw do
  resources :events do
    resources :speakers
  end
  resources :news

  root 'welcome#index'

end

app/models/event.rb
class Event < ActiveRecord::Base

  has_attached_file :cover_image, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :cover_image, content_type: /\Aimage\/.*\z/

  has_many :speakers, dependent: :destroy

  def as_json(options)
    EventSerializer.new(self).as_json(root: false)
  end

end

app/models/news.rb
class News < ActiveRecord::Base

  has_attached_file :cover_image, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :cover_image, content_type: /\Aimage\/.*\z/

  def as_json(options)
    NewsSerializer.new(self).as_json(root: false)
  end


end

app/models/speaker.rb
class Speaker < ActiveRecord::Base

  has_attached_file :profile_pic, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :profile_pic, content_type: /\Aimage\/.*\z/

  belongs_to :event

  def as_json()
    SpeakerSerializer.new(self).as_json(root: false)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def return_response(data, message, status, error, options)
    result = Hash.new
    result[:data] = Hash.new
    result[:data] = data
    result[:message] = message
    result[:status] = status
    result[:update] = 'false'

    if (error)
      result[:error] = message
    end
    render json: result, status: status, extra_options: options
  end

  private :return_response

  def return_error_response(message, status)
    return_response(nil, message, status, true, nil)
  end

  def return_success_response(data, message, status, options = nil)
    return_response(data, message, status, false, options)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
    respond_to do |format|
      format.html {}
      format.json {
        data = Hash.new
        data["events"] = @events
        return_success_response(data, "Request Successful", 200)
      }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :description, :from_datetime, :to_datetime, :ticket_url, :ticker_price, :venue_title, :venue_lat, :venue_long, :cover_image)
    end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]

  # GET /news
  # GET /news.json
  def index
    @news = News.all
    respond_to do |format|
      format.html {}
      format.json {
        data = Hash.new
        data["news"] = @news
        return_success_response(data, "Request Successful", 200)
      }
    end
  end

  # GET /news/1
  # GET /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url, notice: 'News was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:title, :content, :url, :cover_image)
    end
end

app/controllers/speakers_controller.rb
class SpeakersController < ApplicationController

  def create
    @event = Event.find(params[:event_id])
    @speaker = @event.speakers.create(speaker_params)
    redirect_to event_path(@event)
  end

  def destroy
    @event = Event.find(params[:event_id])
    @speaker = @event.speakers.find(params[:id])
    @speaker.destroy
    redirect_to event_path(@event)
  end

  private
  def speaker_params
    params.require(:speaker).permit(:name, :bio, :profile_url, :profile_pic)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController


  def index

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/speakers_helper.rb
module SpeakersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :from_datetime %><br>
    <%= f.datetime_select :from_datetime %>
  </div>
  <div class="field">
    <%= f.label :to_datetime %><br>
    <%= f.datetime_select :to_datetime %>
  </div>
  <div class="field">
    <%= f.label :ticket_url %><br>
    <%= f.text_field :ticket_url %>
  </div>
  <div class="field">
    <%= f.label :ticker_price %><br>
    <%= f.number_field :ticker_price %>
  </div>
  <div class="field">
    <%= f.label :venue_title %><br>
    <%= f.text_field :venue_title %>
  </div>
  <div class="field">
    <%= f.label :venue_lat %><br>
    <%= f.text_field :venue_lat %>
  </div>
  <div class="field">
    <%= f.label :venue_long %><br>
    <%= f.text_field :venue_long %>
  </div>
    <div class="field">
      <%= f.file_field :cover_image %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Events</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>From datetime</th>
      <th>To datetime</th>
      <th>Ticket url</th>
      <th>Ticker price</th>
      <th>Venue title</th>
      <th>Venue lat</th>
      <th>Venue long</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.description %></td>
        <td><%= event.from_datetime %></td>
        <td><%= event.to_datetime %></td>
        <td><%= event.ticket_url %></td>
        <td><%= event.ticker_price %></td>
        <td><%= event.venue_title %></td>
        <td><%= event.venue_lat %></td>
        <td><%= event.venue_long %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p> <%= image_tag @event.cover_image %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>From datetime:</strong>
  <%= @event.from_datetime %>
</p>

<p>
  <strong>To datetime:</strong>
  <%= @event.to_datetime %>
</p>

<p>
  <strong>Ticket url:</strong>
  <%= @event.ticket_url %>
</p>

<p>
  <strong>Ticker price:</strong>
  <%= @event.ticker_price %>
</p>

<p>
  <strong>Venue title:</strong>
  <%= @event.venue_title %>
</p>

<p>
  <strong>Venue lat:</strong>
  <%= @event.venue_lat %>
</p>

<p>
  <strong>Venue long:</strong>
  <%= @event.venue_long %>
</p>

<h2>Speakers:</h2>
<% @event.speakers.each do |speaker| %>
    <p>
      <%= image_tag speaker.profile_pic %>
    </p>

    <p>
      <strong>Name:</strong>
      <%= speaker.name %>
    </p>

    <p>
      <strong>Bio:</strong>
      <%= speaker.bio %>
    </p>
    <p>
      <strong>Profile Url:</strong>
      <%= speaker.profile_url %>
    </p>
    <p>
      <%= link_to 'Destroy Speaker', [speaker.event, speaker],
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %>
    </p>
<% end %>

<h2>Add a speaker:</h2>
<%= form_for([@event, @event.speakers.build]) do |sf| %>
    <p>
      <%= sf.label :name %><br>
      <%= sf.text_field :name %>
    </p>
    <p>
      <%= sf.label :bio %><br>
      <%= sf.text_area :bio %>
    </p>
    <p>
      <%= sf.label :profile_url %><br>
      <%= sf.text_field :profile_url %>
    </p>
    <p>
      <%= sf.file_field :profile_pic %>
    </p>
    <p>
      <%= sf.submit %>
    </p>
<% end %>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Capstone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/news/_form.html.erb
<%= form_for(@news) do |f| %>
  <% if @news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% @news.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.file_field :cover_image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/news/edit.html.erb
<h1>Editing News</h1>

<%= render 'form' %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

app/views/news/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing News</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @news.each do |news| %>
      <tr>
        <td><%= news.title %></td>
        <td><%= news.content %></td>
        <td><%= news.url %></td>
        <td><%= link_to 'Show', news %></td>
        <td><%= link_to 'Edit', edit_news_path(news) %></td>
        <td><%= link_to 'Destroy', news, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New News', new_news_path %>

app/views/news/new.html.erb
<h1>New News</h1>

<%= render 'form' %>

<%= link_to 'Back', news_index_path %>

app/views/news/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= image_tag @news.cover_image %>

</p>

<p>
  <strong>Title:</strong>
  <%= @news.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @news.content %>
</p>

<p>
  <strong>Url:</strong>
  <%= @news.url %>
</p>

<%= link_to 'Edit', edit_news_path(@news) %> |
<%= link_to 'Back', news_index_path %>

app/views/welcome/index.html.erb
<h1> Welcome to Rohan's Capstone Project. </h1>